name: ignite
description: "Final Project"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  dio: ^5.7.0

  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.1
  path: ^1.8.3
  drift: ^2.22.1
  drift_flutter: ^0.1.0
  flutter_dotenv: ^5.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.5.4
  retrofit_generator: ^7.0.0
  drift_dev: ^2.22.0
  mockito: ^5.4.2
  bloc_test: ^9.1.4
  mocktail: ^1.0.0
  
flutter:
  uses-material-design: true

  assets:
    - assets/img_1_flutter.png
    - assets/img_2_flutter.png
    - assets/img_3_flutter.png
    - assets/img_4_flutter.png
    - assets/img_5_flutter.png
    - .env